### ISSUE TITLE
Invalid literal for int() error in docket parsing

### ISSUE THREAD

**Issue by adamrlinder** [CodeForPhilly/pbf-scraping#43]
A handful of dockets returned the below error when running them through the parsing script. I've attached an example of one. 

[MC-51-CR-0003447-2020.pdf](https://github.com/CodeForPhilly/pbf-scraping/files/5392126/MC-51-CR-0003447-2020.pdf)

```
Traceback (most recent call last):
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/one_time_parse.py", line 24, in <module>
    parse = parse_pdf(path_folder+file, text)
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/parse_docket.py", line 139, in parse_pdf
    result['bail_set_by'] = get_bail(pdf,pages_bail)
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/funcs_parse.py", line 125, in get_bail
    bail,bail_type = bail_set(pdf,p,y2_1,y1_0,x1_0,x1_0+200,bail,bail_type)
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/funcs_parse.py", line 84, in bail_set
    if int(info[0]) == int(n_lines[-1-(k-1)]):
ValueError: invalid literal for int() with base 10: 'Guilty'
```

**Comment by bertamb** [comment]
Solved
