### ISSUE TITLE
Float() argument must be a string or number error in docket parsing

### ISSUE THREAD

**Issue by adamrlinder** [CodeForPhilly/pbf-scraping#44]
Some dockets returned the below error when parsing. I think in this case it's maybe just that we need to make it say 0 rather than null in cases where no bail is set?

[MC-51-CR-0014122-2020.pdf](https://github.com/CodeForPhilly/pbf-scraping/files/5392144/MC-51-CR-0014122-2020.pdf)

```Traceback (most recent call last):
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/one_time_parse.py", line 31, in <module>
    parse = parse_pdf(path_folder+file, text)
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/parse_docket.py", line 146, in parse_pdf
    result['bail_amount'] = get_bail_info(pdf, pages_bail_info)[0]
  File "/Users/Shared/CFP Scraping/pbf-scraping/analyses/full_dockets/funcs_parse.py", line 141, in get_bail_info
    y3_1 = float(info_3.attr('y1'))
TypeError: float() argument must be a string or a number, not 'NoneType'```

**Comment by bertamb** [comment]
Solved
